### ISSUE TITLE
 java.lang.NoClassDefFoundError: Failed resolution of: Ljava/net/http/HttpClient;

### ISSUE THREAD

**Issue by hoangthanhlong13032000** [jwdeveloper/TikTokLiveJava#104]
i meet this problem when import and run your lib in android app
detail is:
java.lang.NoClassDefFoundError: Failed resolution of: Ljava/net/http/HttpClient;
	at io.github.jwdeveloper.tiktok.http.HttpClient.prepareClient(HttpClient.java:109)
	at io.github.jwdeveloper.tiktok.http.HttpClient.toResponse(HttpClient.java:46)
	at io.github.jwdeveloper.tiktok.http.HttpClient.toJsonResponse(HttpClient.java:72)
	at io.github.jwdeveloper.tiktok.TikTokLiveHttpClient.getGiftsData(TikTokLiveHttpClient.java:113)
	at io.github.jwdeveloper.tiktok.TikTokLiveHttpClient.fetchGiftsData(TikTokLiveHttpClient.java:107)
	at io.github.jwdeveloper.tiktok.TikTokLive.gifts(TikTokLive.java:115)
	at io.github.jwdeveloper.tiktok.TikTokLiveClientBuilder.build(TikTokLiveClientBuilder.java:159)
	at io.github.jwdeveloper.tiktok.TikTokLiveClientBuilder.buildAndConnect(TikTokLiveClientBuilder.java:193)
...
Caused by: java.lang.ClassNotFoundException: Didn't find class "java.net.http.HttpClient" on path: DexPathList[[zip file "/data/app/~~8a4DUfPZukNmq1hOD7QWBA==/htlong.xiii.tiksale-karImReWWqssR4Yc7RlguA==/base.apk"],nativeLibraryDirectories=[/data/app/~~8a4DUfPZukNmq1hOD7QWBA==/htlong.xiii.tiksale-karImReWWqssR4Yc7RlguA==/lib/arm64, /system/lib64, /system_ext/lib64]]
                                                                                                    	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
my app use java 17

**Comment by kohlerpop1** [comment]
Try Java 16 and a different version/type. Seems like whatever Java you compiled is missing the basic classes that should come packaged with it. Unfortunately, this is not something we can fix.
