### ISSUE TITLE
Unable to connect to Mature live chats.

### ISSUE THREAD

**Issue by e3ndr** [jwdeveloper/TikTokLiveJava#12]
This happens even though the host is definitely online. Passing in a Session ID does not fix the issue.

Log:
```
[TikTokLive <REDACTED>] [INFO]: TikTokLive client state: CONNECTING
[TikTokLive <REDACTED>] [INFO]: Fetching room ID
[TikTokLive <REDACTED>] [INFO]: RoomID -> <REDACTED, BUT VALID VALUE>
[TikTokLive <REDACTED>] [INFO]: Fetching RoomInfo
[TikTokLive <REDACTED>] [INFO]: RoomInfo status -> HostNotFound
[TikTokLive <REDACTED>] [INFO]: TikTokLive client state: DISCONNECTED
Exception in thread "main" io.github.jwdeveloper.tiktok.exceptions.TikTokLiveOfflineHostException: LiveStream for Host name could not be found. Is the Host online?
	at io.github.jwdeveloper.tiktok.TikTokLiveClient.tryConnect(TikTokLiveClient.java:143)
	at io.github.jwdeveloper.tiktok.TikTokLiveClient.connect(TikTokLiveClient.java:94)
	at Test.main(Test.java:15)
```

**Comment by e3ndr** [comment]
Looks like `fetchRoomInfo()` is getting a status_code of 4003110.

**Comment by hanpk572000** [comment]
help
