### ISSUE TITLE
java.net.http.HttpConnectTimeoutException: HTTP connect timed out

### ISSUE THREAD

**Issue by SteveNunes** [jwdeveloper/TikTokLiveJava#20]
```
java.net.http.HttpConnectTimeoutException: HTTP connect timed out
	at java.net.http/jdk.internal.net.http.HttpClientImpl.send(HttpClientImpl.java:945)
	at java.net.http/jdk.internal.net.http.HttpClientFacade.send(HttpClientFacade.java:133)
	at io.github.jwdeveloper.tiktok.http.TikTokHttpRequestFactory.getContent(TikTokHttpRequestFactory.java:145)
	at io.github.jwdeveloper.tiktok.http.TikTokHttpRequestFactory.get(TikTokHttpRequestFactory.java:84)
	at io.github.jwdeveloper.tiktok.http.TikTokHttpClient.getRequest(TikTokHttpClient.java:105)
	at io.github.jwdeveloper.tiktok.http.TikTokHttpClient.getJsonFromTikTokApi(TikTokHttpClient.java:65)
	at io.github.jwdeveloper.tiktok.http.TikTokApiService.fetchUserInfoFromTikTokApi(TikTokApiService.java:71)
	at io.github.jwdeveloper.tiktok.http.TikTokApiService.fetchRoomId(TikTokApiService.java:60)
	at io.github.jwdeveloper.tiktok.TikTokLiveClient.tryConnect(TikTokLiveClient.java:140)
	at io.github.jwdeveloper.tiktok.TikTokLiveClient.connect(TikTokLiveClient.java:95)
	at io.github.jwdeveloper.tiktok.TikTokLiveClient.connect(TikTokLiveClient.java:108)
	at io.github.jwdeveloper.tiktok.TikTokLiveClient.connect(TikTokLiveClient.java:108)
	at io.github.jwdeveloper.tiktok.TikTokLiveClient.connect(TikTokLiveClient.java:108)
	at io.github.jwdeveloper.tiktok.TikTokLiveClient.connect(TikTokLiveClient.java:108)
	at io.github.jwdeveloper.tiktok.TikTokLiveClient.connect(TikTokLiveClient.java:108)
	at io.github.jwdeveloper.tiktok.TikTokLiveClient.connect(TikTokLiveClient.java:108)
	at io.github.jwdeveloper.tiktok.TikTokLiveClient.connect(TikTokLiveClient.java:108)
	at io.github.jwdeveloper.tiktok.TikTokLiveClient.lambda$connectAsync$1(TikTokLiveClient.java:88)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
Caused by: java.net.http.HttpConnectTimeoutException: HTTP connect timed out
	at java.net.http/jdk.internal.net.http.MultiExchange.toTimeoutException(MultiExchange.java:585)
	at java.net.http/jdk.internal.net.http.MultiExchange.getExceptionalCF(MultiExchange.java:532)
	at java.net.http/jdk.internal.net.http.MultiExchange.lambda$responseAsyncImpl$7(MultiExchange.java:452)
	at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:934)
	at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:911)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2194)
	at java.net.http/jdk.internal.net.http.Exchange.checkCancelled(Exchange.java:330)
	at java.net.http/jdk.internal.net.http.Exchange.cancel(Exchange.java:293)
	at java.net.http/jdk.internal.net.http.MultiExchange.cancel(MultiExchange.java:265)
	at java.net.http/jdk.internal.net.http.PlainHttpConnection$ConnectTimerEvent.handle(PlainHttpConnection.java:103)
	at java.net.http/jdk.internal.net.http.HttpClientImpl.purgeTimeoutsAndReturnNextDeadline(HttpClientImpl.java:1778)
	at java.net.http/jdk.internal.net.http.HttpClientImpl$SelectorManager.run(HttpClientImpl.java:1376)
Caused by: java.net.ConnectException: HTTP connect timed out
	at java.net.http/jdk.internal.net.http.MultiExchange.toTimeoutException(MultiExchange.java:586)
	```

**Comment by ThreaT** [comment]
Same here, can't connect to any live streams at all
