### ISSUE TITLE
Error while trying to connect into a live

### ISSUE THREAD

**Issue by SteveNunes** [jwdeveloper/TikTokLiveJava#21]
```
io.github.jwdeveloper.tiktok.exceptions.TikTokLiveRequestException: Failed to fetch client data
	at io.github.jwdeveloper.tiktok.http.TikTokApiService.fetchClientData(TikTokApiService.java:122)
	at io.github.jwdeveloper.tiktok.TikTokLiveClient.tryConnect(TikTokLiveClient.java:159)
	at io.github.jwdeveloper.tiktok.TikTokLiveClient.connect(TikTokLiveClient.java:95)
	at io.github.jwdeveloper.tiktok.TikTokLiveClient.lambda$connectAsync$1(TikTokLiveClient.java:88)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
Caused by: io.github.jwdeveloper.tiktok.exceptions.TikTokLiveRequestException: Unable to deserialize message: im/fetch/
	at io.github.jwdeveloper.tiktok.http.TikTokHttpClient.getSigningServerResponse(TikTokHttpClient.java:86)
	at io.github.jwdeveloper.tiktok.http.TikTokApiService.fetchClientData(TikTokApiService.java:117)
	... 10 more
Caused by: com.google.protobuf.InvalidProtocolBufferException: While parsing a protocol message, the input ended unexpectedly in the middle of a field.  This could mean either that the input has been truncated or that an embedded message misreported its own length.
	at com.google.protobuf.InvalidProtocolBufferException.truncatedMessage(InvalidProtocolBufferException.java:115)
	at com.google.protobuf.CodedInputStream$ArrayDecoder.readRawBytes(CodedInputStream.java:1259)
	at com.google.protobuf.CodedInputStream$ArrayDecoder.readBytes(CodedInputStream.java:910)
	at com.google.protobuf.UnknownFieldSet$Builder.mergeFieldFrom(UnknownFieldSet.java:513)
	at com.google.protobuf.UnknownFieldSet$Builder.mergeFrom(UnknownFieldSet.java:490)
	at com.google.protobuf.UnknownFieldSet$Builder.mergeFrom(UnknownFieldSet.java:603)
	at com.google.protobuf.UnknownFieldSet$Builder.mergeFrom(UnknownFieldSet.java:303)
	at com.google.protobuf.CodedInputStream$ArrayDecoder.readGroup(CodedInputStream.java:833)
	at com.google.protobuf.UnknownFieldSet$Builder.mergeFieldFrom(UnknownFieldSet.java:517)
	at com.google.protobuf.GeneratedMessageV3.parseUnknownField(GeneratedMessageV3.java:332)
	at io.github.jwdeveloper.tiktok.messages.webcast.WebcastResponse.<init>(WebcastResponse.java:144)
	at io.github.jwdeveloper.tiktok.messages.webcast.WebcastResponse$1.parsePartialFrom(WebcastResponse.java:2934)
	at io.github.jwdeveloper.tiktok.messages.webcast.WebcastResponse$1.parsePartialFrom(WebcastResponse.java:2928)
	at com.google.protobuf.AbstractParser.parsePartialFrom(AbstractParser.java:158)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:191)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:203)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:208)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:48)
	at io.github.jwdeveloper.tiktok.messages.webcast.WebcastResponse.parseFrom(WebcastResponse.java:1672)
	at io.github.jwdeveloper.tiktok.http.TikTokHttpClient.getSigningServerResponse(TikTokHttpClient.java:82)
	... 11 more
	```

**Comment by jwdeveloper** [comment]
propably fixed
