### ISSUE TITLE
error.

### ISSUE THREAD

**Issue by JxstColin** [jwdeveloper/TikTokLiveJava#6]
[15:08:33] [Server thread/ERROR]: Error occurred while enabling TikTokLive v1.0 (Is it up to date?)
io.github.jwdeveloper.tiktok.exceptions.TikTokLiveRequestException: Failed to fetch client data
        at io.github.jwdeveloper.tiktok.http.TikTokApiService.fetchClientData(TikTokApiService.java:158) ~[?:?]
        at io.github.jwdeveloper.tiktok.TikTokLiveClient.tryConnect(TikTokLiveClient.java:101) ~[?:?]
        at io.github.jwdeveloper.tiktok.TikTokLiveClient.connect(TikTokLiveClient.java:50) ~[?:?]
        at io.github.jwdeveloper.tiktok.TikTokLiveClientBuilder.buildAndRun(TikTokLiveClientBuilder.java:111) ~[?:?]
        at eu.jxstcolin.main.Main.onEnable(Main.java:33) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:546) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3870-Spigot-d2eba2c-78796c9]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:460) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3870-Spigot-d2eba2c-78796c9]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:588) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3870-Spigot-d2eba2c-78796c9]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:413) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3870-Spigot-d2eba2c-78796c9]
        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:250) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3870-Spigot-d2eba2c-78796c9]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:972) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3870-Spigot-d2eba2c-78796c9]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:303) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3870-Spigot-d2eba2c-78796c9]
        at java.lang.Thread.run(Thread.java:1623) ~[?:?]
Caused by: io.github.jwdeveloper.tiktok.exceptions.TikTokLiveRequestException: Unable to deserialize message: im/fetch/
        at io.github.jwdeveloper.tiktok.http.TikTokHttpClient.getDeserializedMessage(TikTokHttpClient.java:61) ~[?:?]
        at io.github.jwdeveloper.tiktok.http.TikTokApiService.fetchClientData(TikTokApiService.java:153) ~[?:?]
        ... 15 more
Caused by: com.google.protobuf.InvalidProtocolBufferException: While parsing a protocol message, the input ended unexpectedly in the middle of a field.  This could mean either that the input has been truncated or that an embedded message misreported its own length.
        at com.google.protobuf.InvalidProtocolBufferException.truncatedMessage(InvalidProtocolBufferException.java:115) ~[protobuf-java-3.21.9.jar:?]
        at com.google.protobuf.CodedInputStream$ArrayDecoder.readRawBytes(CodedInputStream.java:1265) ~[protobuf-java-3.21.9.jar:?]
        at com.google.protobuf.CodedInputStream$ArrayDecoder.readBytes(CodedInputStream.java:916) ~[protobuf-java-3.21.9.jar:?]
        at com.google.protobuf.UnknownFieldSet$Builder.mergeFieldFrom(UnknownFieldSet.java:514) ~[protobuf-java-3.21.9.jar:?]
        at com.google.protobuf.UnknownFieldSet$Builder.mergeFrom(UnknownFieldSet.java:491) ~[protobuf-java-3.21.9.jar:?]
        at com.google.protobuf.UnknownFieldSet$Builder.mergeFrom(UnknownFieldSet.java:604) ~[protobuf-java-3.21.9.jar:?]
        at com.google.protobuf.UnknownFieldSet$Builder.mergeFrom(UnknownFieldSet.java:304) ~[protobuf-java-3.21.9.jar:?]
        at com.google.protobuf.CodedInputStream$ArrayDecoder.readGroup(CodedInputStream.java:837) ~[protobuf-java-3.21.9.jar:?]
        at com.google.protobuf.UnknownFieldSet$Builder.mergeFieldFrom(UnknownFieldSet.java:518) ~[protobuf-java-3.21.9.jar:?]
        at com.google.protobuf.GeneratedMessageV3.parseUnknownField(GeneratedMessageV3.java:325) ~[protobuf-java-3.21.9.jar:?]
        at io.github.jwdeveloper.tiktok.messages.WebcastResponse.<init>(WebcastResponse.java:123) ~[?:?]
        at io.github.jwdeveloper.tiktok.messages.WebcastResponse$1.parsePartialFrom(WebcastResponse.java:3249) ~[?:?]
        at io.github.jwdeveloper.tiktok.messages.WebcastResponse$1.parsePartialFrom(WebcastResponse.java:3243) ~[?:?]
        at com.google.protobuf.AbstractParser.parsePartialFrom(AbstractParser.java:158) ~[protobuf-java-3.21.9.jar:?]
        at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:191) ~[protobuf-java-3.21.9.jar:?]
        at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:203) ~[protobuf-java-3.21.9.jar:?]
        at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:208) ~[protobuf-java-3.21.9.jar:?]
        at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:48) ~[protobuf-java-3.21.9.jar:?]
        at io.github.jwdeveloper.tiktok.messages.WebcastResponse.parseFrom(WebcastResponse.java:1999) ~[?:?]
        at io.github.jwdeveloper.tiktok.http.TikTokHttpClient.getDeserializedMessage(TikTokHttpClient.java:57) ~[?:?]
        at io.github.jwdeveloper.tiktok.http.TikTokApiService.fetchClientData(TikTokApiService.java:153) ~[?:?]
        ... 15 more

**Comment by jwdeveloper** [comment]
Try to use lastest version
